sudo: false

matrix:
  include:

    # - language: common-lisp

    - language: julia
      julia: 1.1
      before_script:
        - cd julia/OverlapIntegrals

    # Cribbed from
    # https://github.com/mratsim/Arraymancer/blob/407cae439d5f1f76431251c28a7e6fc9652444e3/.travis.yml#L66
    - language: c # nim
      before_install:
        - export CHANNEL=stable
        - export CHOOSENIM_NO_ANALYTICS=1
        - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        - sh init.sh -y
        - export PATH=~/.nimble/bin:$PATH
        - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
        - choosenim $CHANNEL
      before_script:
        - cd nim
      script:
        - nim c -r overlapintegrals.nim

    - language: python
      python: 3.7
      before_install:
        - cd python
        - pip install -r requirements.txt
      script:
        - python -m pytest

    # Cribbed from
    # https://github.com/greghendershott/travis-racket/blob/2945afacf99c9109ee79d92f6f04c08b27be22fe/.travis.yml#L63
    - language: c # racket
      before_install:
        - export RACKET_VERSION=7.5
        - export RACKET_DIR=~/racket
        # Repo history and other branches aren't useful here, so do a shallow
        # clone to only download the tip of the master branch of the repo.
        - git clone --depth 1 https://github.com/greghendershott/travis-racket.git
        - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
        - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
      before_script:
        - cd racket
      script:
        - raco test .

    - language: rust
      rust: stable
      cache: cargo
      before_install:
        cd rust/overlapintegrals
