sudo: false

matrix:
  include:
    # - language: common-lisp
    - language: julia
      julia: 1.1
      before_script:
        - cd julia/OverlapIntegrals
    - language: python
      python: 3.7
      before_script:
        - cd python
      script:
        - python -m pytest
    # - language: racket
    # - language: rust
