sudo: false

matrix:
  include:
    # - language: common-lisp
    - language: julia
      julia: 1.1
      before_script:
        - cd julia/OverlapIntegrals
    - language: python
      python: 3.7
      before_install:
        - cd python
        - pip install -r requirements.txt
      script:
        - python -m pytest
    - language: c # racket
      before_install:
        - export RACKET_VERSION=7.5
        - export RACKET_DIR=~/racket
        # Repo history and other branches aren't useful here, so do a shallow
        # clone to only download the tip of the master branch of the repo.
        - git clone --depth 1 https://github.com/greghendershott/travis-racket.git
        - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
        - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
      before_script:
        - cd racket
      script:
        - raco test .
    # - language: rust
