name = "OverlapIntegrals"
uuid = "2eb46808-55ff-422c-bbae-785d3f66ca36"
authors = ["Eric Berquist <eric.berquist@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
